// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: translation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Original      string                 `protobuf:"bytes,3,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_translation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TranslateRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TranslateRequest) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type TranslateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   string                 `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_translation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

type HistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Original      string                 `protobuf:"bytes,3,opt,name=original,proto3" json:"original,omitempty"`
	Translation   string                 `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryItem) Reset() {
	*x = HistoryItem{}
	mi := &file_translation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryItem) ProtoMessage() {}

func (x *HistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryItem.ProtoReflect.Descriptor instead.
func (*HistoryItem) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HistoryItem) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *HistoryItem) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *HistoryItem) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_translation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{3}
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*HistoryItem         `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_translation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_translation_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetHistory() []*HistoryItem {
	if x != nil {
		return x.History
	}
	return nil
}

var File_translation_proto protoreflect.FileDescriptor

const file_translation_proto_rawDesc = "" +
	"\n" +
	"\x11translation.proto\x12\x02v1\"h\n" +
	"\x10TranslateRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\boriginal\x18\x03 \x01(\tR\boriginal\"5\n" +
	"\x11TranslateResponse\x12 \n" +
	"\vtranslation\x18\x01 \x01(\tR\vtranslation\"\x85\x01\n" +
	"\vHistoryItem\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\boriginal\x18\x03 \x01(\tR\boriginal\x12 \n" +
	"\vtranslation\x18\x04 \x01(\tR\vtranslation\"\x13\n" +
	"\x11GetHistoryRequest\"?\n" +
	"\x12GetHistoryResponse\x12)\n" +
	"\ahistory\x18\x01 \x03(\v2\x0f.v1.HistoryItemR\ahistory2\x84\x01\n" +
	"\vTranslation\x128\n" +
	"\tTranslate\x12\x14.v1.TranslateRequest\x1a\x15.v1.TranslateResponse\x12;\n" +
	"\n" +
	"GetHistory\x12\x15.v1.GetHistoryRequest\x1a\x16.v1.GetHistoryResponseB\x1dZ\x1binternal/controller/grpc/v1b\x06proto3"

var (
	file_translation_proto_rawDescOnce sync.Once
	file_translation_proto_rawDescData []byte
)

func file_translation_proto_rawDescGZIP() []byte {
	file_translation_proto_rawDescOnce.Do(func() {
		file_translation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translation_proto_rawDesc), len(file_translation_proto_rawDesc)))
	})
	return file_translation_proto_rawDescData
}

var file_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_translation_proto_goTypes = []any{
	(*TranslateRequest)(nil),   // 0: v1.TranslateRequest
	(*TranslateResponse)(nil),  // 1: v1.TranslateResponse
	(*HistoryItem)(nil),        // 2: v1.HistoryItem
	(*GetHistoryRequest)(nil),  // 3: v1.GetHistoryRequest
	(*GetHistoryResponse)(nil), // 4: v1.GetHistoryResponse
}
var file_translation_proto_depIdxs = []int32{
	2, // 0: v1.GetHistoryResponse.history:type_name -> v1.HistoryItem
	0, // 1: v1.Translation.Translate:input_type -> v1.TranslateRequest
	3, // 2: v1.Translation.GetHistory:input_type -> v1.GetHistoryRequest
	1, // 3: v1.Translation.Translate:output_type -> v1.TranslateResponse
	4, // 4: v1.Translation.GetHistory:output_type -> v1.GetHistoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_translation_proto_init() }
func file_translation_proto_init() {
	if File_translation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translation_proto_rawDesc), len(file_translation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translation_proto_goTypes,
		DependencyIndexes: file_translation_proto_depIdxs,
		MessageInfos:      file_translation_proto_msgTypes,
	}.Build()
	File_translation_proto = out.File
	file_translation_proto_goTypes = nil
	file_translation_proto_depIdxs = nil
}
