version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: core-platform-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: core_db
    volumes:
    - postgres_data:/var/lib/postgresql/data
    restart: always
    expose:
    - "5432"
  migrate:
    image: migrate/migrate
    volumes:
    - ./migrations:/migrations
    environment:
    - MIGRATE_SOURCE=file://migrations
    - MIGRATE_DATABASE=postgres://user:password@postgres:5432/core_db?sslmode=disable
    command: up
    depends_on:
    - postgres
  nats:
    image: nats:latest
    container_name: core-platform-nats
    restart: always
    expose:
    - "4222"
    - "8222"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: core-platform-rmq
    restart: always
    expose:
    - "5672"
    - "15672"
volumes:
  postgres_data:
